apiVersion: v1   
kind: Pod       
metadata:        
  name: web
  labels:
    app: web
spec:                
  containers:        
  - name: chatapp   
    image: admjake/chatapp:App     
    env:
    - name: "PORT"
      value: "8080" 